# Generated by Django 5.0.2 on 2024-02-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_accepted',
        ),
    ]
