# Generated by Django 5.0.2 on 2024-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_customer_username_professional_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='professional',
            name='password',
            field=models.CharField(default='hello', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='specialization',
            field=models.CharField(choices=[('CONTRACTOR', 'contractor'), ('ARCHITECT', 'architect'), ('SUPERVISOR', 'supervisor'), ('DESIGNER', 'interior designer')], default='contractor', max_length=20),
            preserve_default=False,
        ),
    ]
