# Generated by Django 5.0.2 on 2024-02-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_question_remove_answer_score_answer_answer_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
