# Generated by Django 5.0.2 on 2024-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_question_specialization_answerjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_question_special',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
