# Generated by Django 5.0.2 on 2024-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_question_num_question_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
