# Generated by Django 5.0.2 on 2024-02-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_professional_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='duration',
        ),
    ]
