# Generated by Django 5.0.2 on 2024-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_jobdetail_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='text',
            field=models.TextField(default='No explanation provided'),
            preserve_default=False,
        ),
    ]
