# Generated by Django 5.0.2 on 2024-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_professional_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='project_ended',
            field=models.BooleanField(default=False),
        ),
    ]
