# Generated by Django 5.0.2 on 2024-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_jobdetail_end_time_jobdetail_project_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
