# Generated by Django 5.0.6 on 2024-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_jobdetail_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapproval',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
